# Generated by Django 4.2.3 on 2023-07-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.SlugField(unique=True)),
                ('sector', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('country', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
            ],
        ),
    ]
